#!/bin/sh

echo ""
echo '----------------------'
echo ' Verify dependencies'
echo '----------------------'
go mod verify

echo ""
echo '----------------------'
echo ' Run: go build'
echo '----------------------'
go build -v ./...

echo ""
echo '----------------------'
echo ' Install: golangci-lint'
echo '----------------------'
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.0

echo ""
echo '----------------------'
echo ' Run: golangci'
echo '----------------------'
golangci-lint run ./...

echo ""
echo '----------------------'
echo ' Run: go test'
echo '----------------------'
go test -race -covermode=atomic ./...

echo ""
echo '----------------------'
echo ' Run: goreportcard'
echo '----------------------'
goreportcard-cli -v

echo ""
echo '----------------------'
echo ' Install locally'
echo '----------------------'
go install github.com/sveltinio/sveltin

echo ""
echo '----------------------'
echo ' Check Installation'
echo '----------------------'
sveltin -v

echo ""
